target 'MicroLights' do
  use_frameworks!

  project 'MicroLights.xcodeproj'
  platform :ios, '14.0'
  
  pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
  pod 'OpenSSL-Universal'

end
